version: 2

sources:
  - name: airbyte_internal
    schema: airbyte_internal
    tables:
      - name: dbo_raw__stream_vwlzs_asnaf

models:
  - name: transform_airbyte_data
    description: "Transform Airbyte JSON data into structured format"
    columns:
      - name: AsnafID
        description: "Asnaf ID"
      - name: AsnafName
        description: "Asnaf Name"
      - name: Emel
        description: "Email"
      - name: Age
        description: "Age"
