version: 2

models:
  - name: transform_airbyte_data
    description: "Transform Airbyte JSON data into structured format"
    columns:
      - name: AsnafID
        description: "Asnaf ID"
      - name: AsnafName
        description: "Asnaf Name"
      - name: Emel
        description: "Email"
      - name: Age
        description: "Age"
